version: '3'
services:
  exercisecabify:
    build: .
    ports:
      - "9001:9001"
  messageapp:
    image: "cabify/backend-bootcamp-messageapp:latest"
    ports:
      - "3000:3000"
  mongo:
    depends_on:
      - messageapp
    image: "mongo:5.0.8-focal"
    volumes:
      - ./db:/db
    ports:
      - "27017:27017"
    command: 
      - "--logpath"
      - "/var/log/mongodb/mongod.log"


